export * from './auth';
export * from './news';
export * from './events';
export * from './galleries';
export * from './academic';
export * from './admissions';
export * from './studentServices';
export * from './partnerships';
export * from './profiles';